#!/usr/bin/env python3
"""Generate info_anim_lut.h: 33-entry easing tables (0..1024) for the
TomTom info-panel animation.  Run on the PC; the device never does floats.

  material : cubic-bezier(0.4, 0.0, 0.2, 1.0)   (Material standard)
  css_ease : cubic-bezier(0.25, 0.1, 0.25, 1.0) (CSS 'ease')
"""
import sys

N = 33          # entries; step = 32 units of the 0..1024 input
SCALE = 1024


def bezier_y(x, x1, y1, x2, y2):
    """y for a given x on a CSS cubic-bezier, solved by bisection."""
    def cx(t):
        return 3 * (1 - t) ** 2 * t * x1 + 3 * (1 - t) * t ** 2 * x2 + t ** 3

    def cy(t):
        return 3 * (1 - t) ** 2 * t * y1 + 3 * (1 - t) * t ** 2 * y2 + t ** 3

    lo, hi = 0.0, 1.0
    for _ in range(60):
        mid = (lo + hi) / 2
        if cx(mid) < x:
            lo = mid
        else:
            hi = mid
    return cy((lo + hi) / 2)


def table(x1, y1, x2, y2):
    vals = [round(bezier_y(i / (N - 1), x1, y1, x2, y2) * SCALE)
            for i in range(N)]
    vals[0], vals[-1] = 0, SCALE
    assert all(b >= a for a, b in zip(vals, vals[1:])), "must be monotone"
    return vals


def max_error(vals, x1, y1, x2, y2):
    """Worst gap between linear interpolation of the table and the true curve."""
    worst = 0.0
    for t in range(0, SCALE + 1):
        i, f = min(t >> 5, N - 2), (t & 31)
        approx = vals[i] + (vals[i + 1] - vals[i]) * f / 32.0
        exact = bezier_y(t / SCALE, x1, y1, x2, y2) * SCALE
        worst = max(worst, abs(approx - exact))
    return worst


def emit(name, vals):
    rows = []
    for i in range(0, N, 8):
        rows.append("    " + ", ".join("%4d" % v for v in vals[i:i + 8]))
    return "static const unsigned short %s[%d] = {\n%s\n};\n" % (
        name, N, ",\n".join(rows))


CURVES = {
    "ia_lut_material": (0.4, 0.0, 0.2, 1.0),
    "ia_lut_css_ease": (0.25, 0.1, 0.25, 1.0),
}

if __name__ == "__main__":
    out = ["/* Generated by gen_ease_lut.py - do not edit by hand. */",
           "#ifndef INFO_ANIM_LUT_H", "#define INFO_ANIM_LUT_H", ""]
    for name, curve in CURVES.items():
        vals = table(*curve)
        err = max_error(vals, *curve)
        sys.stderr.write("%s: max interpolation error %.2f / 1024\n" % (name, err))
        assert err < 4.0
        out.append(emit(name, vals))
    out.append("#endif")
    open("info_anim_lut.h", "w").write("\n".join(out) + "\n")
