/* Generated by gen_ease_lut.py - do not edit by hand. */
#ifndef INFO_ANIM_LUT_H
#define INFO_ANIM_LUT_H

static const unsigned short ia_lut_material[33] = {
       0,    2,    9,   23,   44,   75,  117,  172,
     242,  324,  411,  496,  573,  641,  700,  751,
     794,  832,  864,  892,  916,  937,  954,  970,
     982,  993, 1002, 1009, 1015, 1019, 1022, 1023,
    1024
};

static const unsigned short ia_lut_css_ease[33] = {
       0,   18,   47,   87,  140,  203,  273,  346,
     418,  487,  550,  608,  661,  708,  750,  788,
     822,  852,  878,  902,  923,  941,  958,  971,
     984,  994, 1002, 1009, 1015, 1019, 1022, 1023,
    1024
};

#endif
